### ISSUE TITLE
Exception in 1.2.1

### ISSUE THREAD

**Issue by flukejones** [iBavtovich/day-and-night-plugin#5] opened 2019-06-22 21:23 UTC
Not sure what caused it, but recently got this:

```
java.lang.NullPointerException
	at com.daynight.plugin.actions.QuickSwitchAction.actionPerformed(QuickSwitchAction.java:23)
	at com.daynight.plugin.components.QuickChangeStatusBarWidget.lambda$getClickConsumer$0(QuickChangeStatusBarWidget.java:67)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl$IconPresentationWrapper$1.mousePressed(IdeStatusBarImpl.java:767)
	at java.awt.Component.processMouseEvent(Component.java:6547)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by iBavtovich** [comment] 2019-06-23 14:16
Is it happened every time, when you try to switch color theme manually? Or it is some kind of rare situation? May be you can write some step to reproduce?

**Comment by iBavtovich** [comment] 2019-06-28 10:00
@Luke-Nukem hi! Any updates?

**Comment by Luke-Nukem** [comment] 2019-07-21 20:49
@iBavtovich sorry no, though it does appear to happen if resuming from hibernation, then clicking the statusbar icon to switch theme. It *might* be related to how soon it is clicked after resume?

**Comment by iBavtovich** [comment] 2019-07-22 10:42
Yeah, I think so. I will try to dice deeper into this problem

**Comment by iBavtovich** [comment] 2019-10-12 11:15
Hi @Luke-Nukem. New version with fix will be released in approximately 2 working days. Can you please check if this NPE still observed? Because I can't reproduce on Windows machine

**Comment by iBavtovich** [comment] 2019-10-22 08:27
@Luke-Nukem hi! Do you have any news about this fix work?

**Comment by Luke-Nukem** [comment] 2019-11-04 19:26
Hi very sorry about delay in replying. Just been flatout busy. It looks like this is solved.

**Comment by iBavtovich** [comment] 2019-11-05 07:12
Thanks for response :)

**Closed by iBavtovich** 2019-11-05 07:12 UTC
Labels: bug
